export const CONST = {
  INIT_DEPOSIT: '5.00',
  MIN_WITHDRAWAL: 1,
  MINIMUM_ACCOUNT_BALANCE: 10,
  BEGINNER_ACCOUNT_LIMIT: 50,
  INTERMEDIATE_ACCOUNT_LIMIT: 500,
  ADVANCE_ACCOUNT_LIMIT: 5000,
  BEZO_LOCK_INTEREST: '9%',
  BEZO_FLEX_INTEREST: '1%',
  BEZO_LOCK_CHARGES: '5-10%',
  BEZO_FLEX_CHARGES: '3%',
  CHANNEL: 'web',
};
